name: Build and Push API to ECR

on:
  push:
    branches:
      - aws-terraform-infra

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: assal-kolhapuri-api

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Debug GitHub OIDC Claims
        uses: github/actions-oidc-debugger@main
        with:
          audience: sts.amazonaws.com

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::104367407330:role/assal-kolhapuri-github-actions-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify AWS identity
        run: |
          aws sts get-caller-identity

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build \
            -t $ECR_REGISTRY/${ECR_REPOSITORY}:${GITHUB_SHA} \
            -t $ECR_REGISTRY/${ECR_REPOSITORY}:latest \
            .

      - name: Push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker push $ECR_REGISTRY/${ECR_REPOSITORY}:${GITHUB_SHA}
          docker push $ECR_REGISTRY/${ECR_REPOSITORY}:latest
